### ISSUE TITLE
Manual configuration /etc/kubernetes/azure.json permission denied error 

### ISSUE THREAD

**Issue by dhei** [Azure/kubernetes-kms#111]
Hello,

Thanks for shipping v0.0.12 that fixes issue #98. Really appreciate it.

I am trying to follow [manual configuration guide](https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md) with v0.0.12 release and ran into a permission defined error when accessing `/etc/kubernetes/azure.json`.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: azure-kms-provider
  namespace: kube-system
  labels:
    component: azure-kms-provider
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  containers:
    - name: azure-kms-provider
      image: mcr.microsoft.com/oss/azure/kms/keyvault:v0.0.12
      imagePullPolicy: IfNotPresent
      args:
        - --listen-addr=unix:///opt/azurekms.socket             # [OPTIONAL] gRPC listen address. Default is unix:///opt/azurekms.socket
        - --keyvault-name=${KV_Name}                 # [REQUIRED] Name of the keyvault
        - --key-name=${KEY_NAME}                             # [REQUIRED] Name of the keyvault key used for encrypt/decrypt
        - --key-version=${KEY_VERSION}        # [REQUIRED] Version of the key to use
        - --log-format-json=false                               # [OPTIONAL] Set log formatter to json. Default is false.
        - --healthz-port=8787                                   # [OPTIONAL] port for health check. Default is 8787
        - --healthz-path=/healthz                               # [OPTIONAL] path for health check. Default is /healthz
        - --healthz-timeout=20s                                 # [OPTIONAL] RPC timeout for health check. Default is 20s
        - -v=1
      ports:
        - containerPort: 8787                                   # Must match the value defined in --healthz-port
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthz                                        # Must match the value defined in --healthz-path
          port: 8787                                            # Must match the value defined in --healthz-port
        failureThreshold: 2
        periodSeconds: 10
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 4
          memory: 2Gi
      volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-ssl
          mountPath: /etc/ssl
          readOnly: true
        - name: sock
          mountPath: /opt
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-ssl
      hostPath:
        path: /etc/ssl
    - name: sock
      hostPath:
        path: /opt
```

```
kubectl logs azure-kms-provider -n kube-system            

I0624 23:19:44.569846       1 exporter.go:17] metrics backend: prometheus
I0624 23:19:44.570057       1 prometheus_exporter.go:32] "Prometheus metrics server running" address="8095"
I0624 23:19:44.570101       1 main.go:70] "Starting KeyManagementServiceServer service" version="v0.0.12" buildDate="2021-06-09-23:56"
F0624 23:19:44.570128       1 main.go:73] failed to create server, error: failed to load config file /etc/kubernetes/azure.json, error: open /etc/kubernetes/azure.json: permission denied
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0000ce000, 0xbb, 0x1c6)
	/agent/_work/1/s/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x118c600, 0xc000000003, 0x0, 0x0, 0xc0000b6000, 0x0, 0xe71434, 0x7, 0x49, 0x0)
	/agent/_work/1/s/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x118c600, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0xc7d69a, 0x22, 0xc0000a6180, 0x1, ...)
	/agent/_work/1/s/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x19a
k8s.io/klog/v2.Fatalf(...)
	/agent/_work/1/s/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514
main.main()
	/agent/_work/1/s/go/src/github.com/Azure/kubernetes-kms/cmd/server/main.go:73 +0x4ae
```

The problem seems to be I didn't mount azure.json so that `azure-kms-provider` pod couldn't find the azure.json. Can you help me understand:
1. What is the recommended way of mounting azure.json so that it's available to azure-kms-provider pod?
2. What do I need to do to avoid getting permission denied error on azure.json?

Thank you so much.

**Comment by aramase** [comment]
@dhei Are you referring to the manual configuration readme from a tag? The yaml you posted above is missing the `securityContext` required to run as root for the plugin.

```yaml
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsUser: 0
```

The YAML file here has the correct spec: https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md#3-deploy-the-kms-plugin

**Comment by dhei** [comment]
@aramase 

Thanks for your help. Really appreciate it.

Does the manual configurations doc intended to be use for AKS-engine not AKS managed cluster? I am asking because [step 5 - Modify /etc/kubernetes/kube-apiserver.yaml](https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md#5-modify-etckuberneteskube-apiserveryaml) asks to modify kube-apiserver which is not modifiable on AKS managed cluster. When I list all the pods on `kube-system` namespace, I don't see any `kube-apiserver-*` pod. If that is the case, how do I modify the kube-apiserver?

**Comment by nilekhc** [comment]
Hello @dhei,
You are right. You cannot modify AKS api server today to add KMS Plugin. AKS team is working on adding AKV KMS Plugin as an add-on to AKS.

cc @sozercan @phillipgibson

**Comment by sozercan** [comment]
@miwithro

**Comment by miwithro** [comment]
@dhei as @nilekhc noted, we have KMS on our roadmap. Which you track here.

https://github.com/Azure/AKS/issues/845

**Comment by aramase** [comment]
Tracking the AKS support for KMS here: https://github.com/Azure/AKS/issues/845.

Closing this issue.
